In [1]:
import numpy as np
import open3d as o3d
import time

def main_visualization_loop():
    # 创建一个可视化窗口
    vis = o3d.visualization.Visualizer()
    vis.create_window(width=800, height=600)

    # 初始化一个点云对象并随机生成一些点云数据
    pointcloud = np.random.rand(100, 3)  # 生成100个点的随机点云
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(pointcloud)

    # 将点云对象添加到可视化对象中
    vis.add_geometry(pcd)

    for i in range(100):  # 循环100次来观察点云的变化
        # 随机生成一些新的点云数据
        pointcloud = np.random.rand(100, 3)  # 生成新的随机点云
        pcd.points = o3d.utility.Vector3dVector(pointcloud)
        
        # 更新显示
        vis.update_geometry(pcd)
        vis.poll_events()
        vis.update_renderer()
        time.sleep(0.1)  # 暂停一小会儿，以便我们可以看到变化

if __name__ == "__main__":
    main_visualization_loop()


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [ ]:
import numpy as np
import open3d as o3d
import time

def main_visualization_loop():
    # 创建一个可视化窗口
    vis = o3d.visualization.Visualizer()
    vis.create_window(width=800, height=600)

    # 初始化一个空的点云对象并将其添加到可视化对象中
    pcd = o3d.geometry.PointCloud()
    vis.add_geometry(pcd)

    while True:
        # 随机生成一些点云数据
        pointcloud = np.random.rand(100, 3)  # 生成100个点的随机点云
        # 更新点云数据并显示
        update_and_display_pointcloud(pointcloud, vis, pcd)
        time.sleep(0.5)  # 暂停一小会儿，以便我们可以看到变化

def update_and_display_pointcloud(pointcloud, visual, pcd):
    # 更新点云对象的点数据
    pcd.points = o3d.utility.Vector3dVector(pointcloud)
    
    # 更新显示
    visual.update_geometry(pcd)
    visual.poll_events()
    visual.update_renderer()

if __name__ == "__main__":
    main_visualization_loop()


In [3]:
import numpy as np

# 创建一个示例矩阵
r = np.array([[100, 200, 300], 
                   [400, 500, 600], 
                   [150, 250, 350],
                   [700, 800, 900]])

# 将第一列元素大于300的行的所有元素都变为0
r[r[:, 0] > 300] = 0
print(r)

[[100 200 300]
 [  0   0   0]
 [150 250 350]
 [  0   0   0]]


In [6]:
import numpy as np

texture_rgb = np.zeros((1, 3))
print(texture_rgb)

[[0. 0. 0.]]


In [7]:
# 假设我们有一个 n 行 3 列的矩阵，这里以 n = 6 为例，并随机生成一些零和非零行
n = 6
matrix = np.random.choice([0, 1, 2, 3, 4, 5], (n, 3))

# 计算非零行的数量
# 使用 all() 函数沿着行的方向检查是否每个元素都是非零
non_zero_rows = np.sum(np.all(matrix != 0, axis=1))

matrix, non_zero_rows



(array([[1, 3, 5],
        [5, 3, 2],
        [1, 2, 0],
        [3, 1, 3],
        [5, 0, 4],
        [1, 1, 5]]),
 4)